name: 'ZJU-nCov-Hitcarder Action'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - username: ZJU_USERNAME
            password: ZJU_PASSWORD
            dingtalk_token: DINGTALK_TOKEN
            pushplus_token: PUSHPLUS_TOKEN
            serverchan_key: SERVERCHAN_KEY
          - username: ZJU_USERNAME2
            password: ZJU_PASSWORD2
            dingtalk_token: DINGTALK_TOKEN2
            pushplus_token: PUSHPLUS_TOKEN2
            serverchan_key: SERVERCHAN_KEY2
    steps:
      - name: Working
        uses: Long0x0/zju-ncov-hitcarder@master
        with:
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
          dingtalk_token: ${{ secrets[matrix.dingtalk_token] }}
          pushplus_token: ${{ secrets[matrix.pushplus_token] }}
          serverchan_key: ${{ secrets[matrix.serverchan_key] }}
